### ISSUE TITLE
feat: 상품 검색 기능 추가 

### ISSUE THREAD

**Issue by 1sol2sol** [1sol2sol/TheCatServant-Life#15]
## Description

> 입력값에 따른 검색 기능을 추가합니다. 

## Todo List

- [x] search/index.tsx
- [x] search/[name].tsx
- [x] api/search/[name].ts
