### ISSUE TITLE
feat: 커뮤니티탭 상품 업로드 기능 추가 

### ISSUE THREAD

**Issue by 1sol2sol** [1sol2sol/TheCatServant-Life#16]
## Description

> 커뮤니티탭의 상품 업로드 기능을 추가 후 업로드 상품 페이지로 이동합니다. 

## Todo List

- [x] community/write.tsx
- [x] community/[id].tsx
- [x] api/posts/index.ts
- [x] api/posts/[id]/index.ts
