### ISSUE TITLE
feat: 커뮤니티 게시글의 궁금해요 기능 추가 

### ISSUE THREAD

**Issue by 1sol2sol** [1sol2sol/TheCatServant-Life#17]
## Description

> 커뮤니티 게시글의 궁금해요 기능을 추가합니다. 

## Todo List

- [x] api/posts/[id]/index.ts
- [x] api/posts/[id]/wonder.ts
- [x] community/[id].tsx
