### ISSUE TITLE
feat: 커뮤니티 글 업로드 시 위치기반으로 작성하는 기능 추가 

### ISSUE THREAD

**Issue by 1sol2sol** [1sol2sol/TheCatServant-Life#21]
## Description

> 커뮤니티 글 업로드시 사용자의 위치를 확인하여 주변 위치에서만 글을 확인 할 수 있는 기능을 추가합니다. 

## Todo List

- [x] api/posts/index.ts
- [x] community/[id].tsx
- [x] community/index.tsx
- [x] community/write.tsx
