### ISSUE TITLE
feat: 내 프로필 홈에서 구매, 판매, 관심 목록을 불러오는 기능 추가

### ISSUE THREAD

**Issue by 1sol2sol** [1sol2sol/TheCatServant-Life#23]
## Description

> 내 프로필 홈에서 구매, 판매, 관심 목록을 불러오는 기능 추가합니다. 

## Todo List

- [x] api/users/[me]/favs.ts
- [x] api/users/[me]/purchases.ts
- [x] api/users/[me]/sales.ts
- [x] profile/bought.tsx
- [x] profile/loved.tsx
- [x] profile/sold.tsx
