### ISSUE TITLE
style: Home(index) 페이지 스타일링

### ISSUE THREAD

**Issue by 1sol2sol** [1sol2sol/TheCatServant-Life#3]
## Description

> 로그인 후 처음 렌더링되는 페이지 스타일링 및 재사용될 floating button, layout, item 컴포넌트 화 

## Todo List

- [x] index.tsx
- [x] components/floating-button.tsx
- [x] components/layout.tsx
- [x] components/item.tsx
