### ISSUE TITLE
style: 커뮤니티 홈, 글쓰기, 상세페이지 스타일링

### ISSUE THREAD

**Issue by 1sol2sol** [1sol2sol/TheCatServant-Life#6]
## Description

> 커뮤니티 탭의 홈, 글쓰기 상세페이지 스타일링

## Todo List

- [x] community/index.tsx
- [x] community/write.tsx
- [x] community/[id].tsx
