### ISSUE TITLE
style: 채팅 목록, 상세페이지 스타일링

### ISSUE THREAD

**Issue by 1sol2sol** [1sol2sol/TheCatServant-Life#7]
## Description

> 유저들의 채팅 목록과 상세페이지 스타일링, 재사용되는 말풍선(메세지) 컴포넌트 화 

## Todo List

- [x] chats/index.tsx
- [x] chats/[id].tsx
- [x] components/message.tsx
