### ISSUE TITLE
style: 프로필 홈, 수정,  관심,  판매, 구매 내역 페이지 스타일링

### ISSUE THREAD

**Issue by 1sol2sol** [1sol2sol/TheCatServant-Life#8]
## Description

> 나의 프로필 홈 렌더링 페이지, 프로필 수정, 나의 관심, 구매, 판매 내역 페이지 스타일링

## Todo List

- [x] profile/index.tsx
- [x] profile/edit.tsx
- [x] profile/bought.tsx
- [x] profile/loved.tsx
- [x] profile/sold.tsx
